@url = http://localhost:3051
	
### EXECUTE SQL
GET {{url}}/api/sql
	
### EXECUTE SQL
GET {{url}}/api/get-pin
	
### GET ALL PETS
GET {{url}}/api/get-pets
	
### ADD A PET
POST {{url}}/api/post-pet
content-type: application/json
	
{
	"name": "Fido",
	"owner": "Mr. Dogowner555"
}

### ADD A NOTE
POST {{url}}/api/add-note
content-type: application/json
	
{
	"body": "This is the second note.",
	"rank": 4.1
}