@url = http://localhost:3051
	
### EXECUTE SQL
GET {{url}}/api/sql
	
### GET ALL PETS
GET {{url}}/api/get-pets
	
### ADD A PET
POST {{url}}/api/post-pet
content-type: application/json
	
{
	"name": "Fido",
	"owner": "Mr. Dogowner555"
}