@url = http://localhost:3051
	
### EXECUTE SQL
GET {{url}}/api/sql
	
### EXECUTE SQL
GET {{url}}/api/get-pin
	
### GET ALL NOTES
GET {{url}}/api/get-notes
	
### ADD A PET
POST {{url}}/api/post-pet
content-type: application/json
	
{
	"name": "Fido",
	"owner": "Mr. Dogowner555"
}

### ADD A NOTE
POST {{url}}/api/add-note
content-type: application/json
	
{
	"app_pin": "123",
	"body": "333This is the third note and here is a lot more text for a long entry, another one.",
	"rank": 2.7
}